In [2]:
import torch 
import numpy as np

In [3]:
a = torch.randn(2,3) # 随机初始化两行三列tensor 服从分布N(0,1)

In [4]:
a.type()


'torch.FloatTensor'

In [4]:
isinstance(a,torch.FloatTensor)

True

In [5]:
a

tensor([[ 1.1543,  0.2631, -0.1043],
        [ 0.4122, -1.1686, -1.5041]])

In [6]:
type(a)

torch.Tensor

In [7]:
torch.tensor(1.)

tensor(1.)

In [8]:
torch.tensor(1.3)

tensor(1.3000)

In [9]:
a = torch.tensor(2.2)

In [10]:
a.shape

torch.Size([])

In [11]:
len(a.shape)

0

In [12]:
a.size()

torch.Size([])

In [13]:
torch.tensor([1.1])

tensor([1.1000])

In [14]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [15]:
torch.FloatTensor(1)

tensor([4.5639e+20])

In [16]:
torch.FloatTensor(2)

tensor([-9.6867e-18,  3.0747e-41])

In [17]:
data = np.ones(2)

In [18]:
data

array([1., 1.])

In [19]:
torch.from_numpy(data) #从numpy引用

tensor([1., 1.], dtype=torch.float64)

In [20]:
a = torch.ones(2)

In [21]:
a.shape

torch.Size([2])

In [22]:
a = torch.randn(2,3)

In [23]:
a

tensor([[ 0.6989,  1.0393,  0.0742],
        [ 0.3323, -0.8819, -0.6748]])

In [24]:
a.shape

torch.Size([2, 3])

In [25]:
a.size(0)

2

In [26]:
a.size(1)

3

In [27]:
a.shape[1]

3

In [28]:
a.shape[0]

2

In [29]:
a = torch.rand(1,2,3)

In [30]:
a

tensor([[[0.1800, 0.8120, 0.7634],
         [0.0146, 0.2605, 0.7042]]])

In [31]:
a.shape

torch.Size([1, 2, 3])

In [32]:
a[0]

tensor([[0.1800, 0.8120, 0.7634],
        [0.0146, 0.2605, 0.7042]])

In [33]:
list(a.shape)

[1, 2, 3]

In [34]:
a[0][1]

tensor([0.0146, 0.2605, 0.7042])

In [35]:
a[0][0]

tensor([0.1800, 0.8120, 0.7634])

In [36]:
a = torch.rand(2,3,28,28)

In [37]:
a

tensor([[[[0.5847, 0.7503, 0.2054,  ..., 0.9330, 0.8512, 0.6260],
          [0.2554, 0.0484, 0.1725,  ..., 0.7555, 0.9000, 0.3616],
          [0.3414, 0.9896, 0.7620,  ..., 0.2687, 0.3715, 0.2562],
          ...,
          [0.0390, 0.9863, 0.9462,  ..., 0.6155, 0.2038, 0.7448],
          [0.0999, 0.6118, 0.1542,  ..., 0.5762, 0.2279, 0.2386],
          [0.7363, 0.6275, 0.2461,  ..., 0.0805, 0.4990, 0.9238]],

         [[0.7863, 0.0714, 0.4669,  ..., 0.4694, 0.3657, 0.5530],
          [0.6109, 0.7406, 0.5919,  ..., 0.0938, 0.0584, 0.7163],
          [0.3911, 0.5502, 0.4271,  ..., 0.1056, 0.2687, 0.6345],
          ...,
          [0.6932, 0.3253, 0.9299,  ..., 0.2840, 0.0210, 0.4084],
          [0.5297, 0.1025, 0.4514,  ..., 0.2333, 0.5046, 0.2146],
          [0.4673, 0.5892, 0.9793,  ..., 0.2755, 0.3914, 0.1291]],

         [[0.8753, 0.7163, 0.1079,  ..., 0.6297, 0.2632, 0.7452],
          [0.4891, 0.1488, 0.8015,  ..., 0.4325, 0.7128, 0.6476],
          [0.0714, 0.7288, 0.6394,  ..., 0

In [38]:
a.shape

torch.Size([2, 3, 28, 28])

In [39]:
a.numel() # mumel是指tensor占用内存的数量

4704

In [40]:
a.dim()

4

In [41]:
a = torch.tensor(1)

In [42]:
a.dim()

0