In [1]:
import torch
import numpy as np

# 从Numpy导入tensor

In [2]:
a = np.array([2,3.3])

In [3]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [4]:
a = np.ones([2,3])

In [6]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# 从list导入tnesor

In [7]:
torch.tensor([2.,3.2])

tensor([2.0000, 3.2000])

In [8]:
torch.FloatTensor([2.,3.2])

tensor([2.0000, 3.2000])

In [9]:
torch.tensor([[2.,3.2],[ 1.,22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [11]:
torch.Tensor(2,3) # 没有初始化的

tensor([[2.0522e+27, 3.0737e-41, 2.0522e+27],
        [3.0737e-41, 8.9683e-44, 0.0000e+00]])

# 生成未初始化的数据

In [12]:
torch.empty(1)

tensor([2.0557e+27])

In [14]:
torch.empty(2,3)

tensor([[-2.5839e-14,  4.5583e-41,  1.4529e+26],
        [ 3.0737e-41,  4.4842e-43,  0.0000e+00]])

In [13]:
torch.Tensor(2,3)

tensor([[2.0559e+27, 3.0737e-41, 2.8195e+26],
        [3.0737e-41, 8.9683e-44, 0.0000e+00]])

In [15]:
torch.IntTensor(2,3)

tensor([[-1461142368,       32529,  1802003888],
        [      21935,          80,           0]], dtype=torch.int32)

In [16]:
torch.FloatTensor(2,3)

tensor([[2.8096e+26, 3.0737e-41, 2.0540e+27],
        [3.0737e-41, 8.9683e-44, 0.0000e+00]])

In [17]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

In [18]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [19]:
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

# 两种常见的随机初始化，rand/rand_like,randint
[0 ,1]
[min, max]
*_like

In [21]:
torch.rand(3,3)

tensor([[0.9109, 0.7080, 0.8310],
        [0.8768, 0.2903, 0.2601],
        [0.8369, 0.8825, 0.8814]])

In [22]:
a = torch.rand(3,3)

In [23]:
torch.rand_like(a)

tensor([[0.7873, 0.2727, 0.3801],
        [0.3268, 0.1292, 0.3971],
        [0.6790, 0.5972, 0.0214]])

In [24]:
torch.randint(1,10,[3,3])

tensor([[6, 9, 1],
        [2, 9, 6],
        [5, 6, 8]])

In [25]:
torch.randn(3,3)

tensor([[ 1.0271, -1.1032,  1.0325],
        [ 1.1053,  1.2308,  0.0766],
        [ 0.1813, -0.0558, -1.7085]])

In [26]:
torch.normal(mean=torch.full([10],0),std=torch.arange(1, 0, -0.1))

tensor([-0.1653,  0.8324,  1.1491,  0.8461, -0.1419,  0.5994,  0.3894,  0.1181,
        -0.4598, -0.0782])

In [27]:
torch.normal(mean=torch.full([10],0),std=torch.arange(1,0,-0.1))

tensor([-1.9751, -0.0350, -1.3892,  0.5051,  0.1794, -0.1970, -0.0143,  0.3036,
         0.4153,  0.0710])

# full 全部赋值为同一个数

In [28]:
torch.full([2,3],7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [29]:
torch.full([],7)

tensor(7.)

In [30]:
torch.full([1],7)

tensor([7.])

# arange / range

In [31]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [33]:
torch.range(0,10)

/home/yan/anaconda3/envs/dataset/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# linspace/logspace

In [4]:
torch.linspace(0,10,steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [6]:
torch.linspace(0, 10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [8]:
torch.linspace(0,10,steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
torch.logspace(0,1,steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

In [11]:
torch.logspace(0,-1,steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

# ones/zeros/eye

In [12]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [17]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
a = torch.eye(4)

In [19]:
torch.ones_like(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# randperm
随机打散，random.shuffle

In [26]:
a = torch.rand(5,4)

In [27]:
b = torch.rand(5,4)

In [28]:
idx = torch.randperm(4)# 生成0~4的随机索引

In [29]:
idx 

tensor([0, 1, 2, 3])

In [30]:
a[idx]

tensor([[0.1046, 0.9641, 0.3414, 0.4592],
        [0.4138, 0.7407, 0.9554, 0.4395],
        [0.6112, 0.9311, 0.3460, 0.8386],
        [0.0386, 0.9679, 0.3001, 0.9628]])

In [31]:
b[idx]

tensor([[0.5319, 0.4913, 0.8708, 0.0666],
        [0.1540, 0.5650, 0.1251, 0.9407],
        [0.4451, 0.1903, 0.4626, 0.7005],
        [0.7310, 0.5573, 0.8341, 0.0651]])

In [32]:
a,b

(tensor([[0.1046, 0.9641, 0.3414, 0.4592],
         [0.4138, 0.7407, 0.9554, 0.4395],
         [0.6112, 0.9311, 0.3460, 0.8386],
         [0.0386, 0.9679, 0.3001, 0.9628],
         [0.4780, 0.0717, 0.4822, 0.1727]]),
 tensor([[0.5319, 0.4913, 0.8708, 0.0666],
         [0.1540, 0.5650, 0.1251, 0.9407],
         [0.4451, 0.1903, 0.4626, 0.7005],
         [0.7310, 0.5573, 0.8341, 0.0651],
         [0.9495, 0.8531, 0.6906, 0.2450]]))