# indexing

In [11]:
import numpy as np
import torch

In [12]:
a = torch.rand(4,3,28,28)

In [13]:
a[0].shape

torch.Size([3, 28, 28])

In [5]:
a[0,0].shape

torch.Size([28, 28])

In [6]:
a[0,0,2,4]

tensor(0.3869)

# select first / lastN

In [7]:
a.shape

torch.Size([4, 3, 28, 28])

In [8]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [9]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [10]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [11]:
a[:2,-1:,:,:].shape  # -1代表最后一个元素

torch.Size([2, 1, 28, 28])

# Select by steps

In [13]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [14]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

# select by mask

In [15]:
x = torch.randn(3,4)

In [16]:
x

tensor([[ 0.5381,  0.9758, -0.0017, -0.4816],
        [-1.1635, -0.2330, -0.3503,  1.0001],
        [ 0.5813,  1.1935,  0.1124, -0.0841]])

In [17]:
mask = x.ge(0.5)

In [18]:
mask

tensor([[ True,  True, False, False],
        [False, False, False,  True],
        [ True,  True, False, False]])

In [19]:
torch.masked_select(x,mask)

tensor([0.5381, 0.9758, 1.0001, 0.5813, 1.1935])

In [20]:
torch.masked_select(x,mask).shape

torch.Size([5])

# select by flatten index

In [21]:
src = torch.tensor([[4,3,3],
                   [6,7,8]])

In [23]:
torch.take(src,torch.tensor([0,2,5])) # 先打平，再用索引

tensor([4, 3, 8])

# view reshape

In [65]:
a = torch.rand(4,1,28,28)

In [66]:
a.shape

torch.Size([4, 1, 28, 28])

In [67]:
a.view(4,28*28)

tensor([[0.9075, 0.6559, 0.8418,  ..., 0.7941, 0.7135, 0.5148],
        [0.8855, 0.6546, 0.2956,  ..., 0.3922, 0.4898, 0.7374],
        [0.8005, 0.6762, 0.4025,  ..., 0.3070, 0.9578, 0.0595],
        [0.6353, 0.6787, 0.7700,  ..., 0.9094, 0.3359, 0.5087]])

In [68]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [69]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [70]:
a.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [71]:
b = a.view(4,784)

In [72]:
b.view(4,28,28,1)  #数据被破坏。数据存储/维度顺序非常重要，需要时刻记住

tensor([[[[0.9075],
          [0.6559],
          [0.8418],
          ...,
          [0.3465],
          [0.3675],
          [0.2752]],

         [[0.1733],
          [0.6155],
          [0.1306],
          ...,
          [0.5125],
          [0.0938],
          [0.2400]],

         [[0.2503],
          [0.5226],
          [0.8873],
          ...,
          [0.5151],
          [0.5988],
          [0.6470]],

         ...,

         [[0.0233],
          [0.7594],
          [0.0186],
          ...,
          [0.0714],
          [0.4642],
          [0.6686]],

         [[0.1777],
          [0.6564],
          [0.9529],
          ...,
          [0.0865],
          [0.0890],
          [0.2790]],

         [[0.9693],
          [0.6472],
          [0.7139],
          ...,
          [0.7941],
          [0.7135],
          [0.5148]]],


        [[[0.8855],
          [0.6546],
          [0.2956],
          ...,
          [0.7821],
          [0.9309],
          [0.5700]],

         [[0.8699],
    

# unsqueeze 

In [73]:
a.shape

torch.Size([4, 1, 28, 28])

In [74]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [75]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [76]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [77]:
a.unsqueeze(-4).shape  # 在-4之后插入，不建议使用负数

torch.Size([4, 1, 1, 28, 28])

In [78]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [81]:
a.unsqueeze(5).shape # 

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 5)

In [82]:
a = torch.tensor([1.2,2.3]) # a 的维度是【2】在-1位置插入一个维度变成了【2,1】

In [83]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [84]:
a.unsqueeze(0) # 在0 位置插入一个维度 变成了【1,2】

tensor([[1.2000, 2.3000]])

In [1]:
# for example 

In [14]:
b = torch.rand(32)

In [15]:
f = torch.rand(4,32,14,14)

In [17]:
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)

In [18]:
b.shape

torch.Size([1, 32, 1, 1])

# squeeze


In [19]:
b.shape

torch.Size([1, 32, 1, 1])

In [21]:
b.squeeze().shape # 不给参数，能被挤压的维度都会被挤压，维度的是1的位置

torch.Size([32])

In [22]:
b.squeeze(0).shape # 挤压0位置的维度

torch.Size([32, 1, 1])

In [23]:
b.squeeze(-1).shape 

torch.Size([1, 32, 1])