In [3]:
import numpy as np
import torch

# view reshape

In [4]:
a = torch.rand(4,1,28,28)

In [5]:
a.shape

torch.Size([4, 1, 28, 28])

In [6]:
a.view(4,28*28)

tensor([[0.0503, 0.8297, 0.5913,  ..., 0.3669, 0.4509, 0.9372],
        [0.7769, 0.2227, 0.4073,  ..., 0.8696, 0.4564, 0.4006],
        [0.2853, 0.6370, 0.4790,  ..., 0.6516, 0.5620, 0.0209],
        [0.7982, 0.2891, 0.6890,  ..., 0.6097, 0.9286, 0.4812]])

In [9]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [10]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [11]:
a.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [12]:
b = a.view(4,784)

In [13]:
b.view(4,28,28,1)  #数据被破坏。数据存储/维度顺序非常重要，需要时刻记住

tensor([[[[0.0503],
          [0.8297],
          [0.5913],
          ...,
          [0.8894],
          [0.1178],
          [0.1813]],

         [[0.1878],
          [0.0164],
          [0.1254],
          ...,
          [0.4887],
          [0.1691],
          [0.8586]],

         [[0.3458],
          [0.2540],
          [0.2990],
          ...,
          [0.2148],
          [0.7624],
          [0.6326]],

         ...,

         [[0.7326],
          [0.4189],
          [0.4451],
          ...,
          [0.7121],
          [0.5764],
          [0.3417]],

         [[0.0888],
          [0.4554],
          [0.0653],
          ...,
          [0.0767],
          [0.9093],
          [0.2428]],

         [[0.8752],
          [0.4297],
          [0.8591],
          ...,
          [0.3669],
          [0.4509],
          [0.9372]]],


        [[[0.7769],
          [0.2227],
          [0.4073],
          ...,
          [0.8695],
          [0.5586],
          [0.5496]],

         [[0.7273],
    

# unsqueeze

In [17]:
a.shape

torch.Size([4, 1, 28, 28])

In [18]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [19]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [20]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [21]:
a.unsqueeze(-4).shape  # 在-4之后插入，不建议使用负数

torch.Size([4, 1, 1, 28, 28])

In [22]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [23]:
a.unsqueeze(5).shape #  超出范围

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)

In [24]:
a = torch.tensor([1.2,2.3]) # a 的维度是【2】在-1位置插入一个维度变成了【2,1】

In [25]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [26]:
a.unsqueeze(0) # 在0 位置插入一个维度 变成了【1,2】

tensor([[1.2000, 2.3000]])

In [27]:
# for example 


In [28]:
b = torch.rand(32)

In [29]:
f = torch.rand(4,32,14,14)

In [30]:
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)

In [31]:
b.shape

torch.Size([1, 32, 1, 1])

# squeeze

In [32]:
b.shape

torch.Size([1, 32, 1, 1])

In [33]:
b.squeeze().shape # 不给参数，能被挤压的维度都会被挤压，维度的是1的位置

torch.Size([32])

In [34]:
b.squeeze(0).shape # 挤压0位置的维度

torch.Size([32, 1, 1])

In [35]:
b.squeeze(-1).shape 

torch.Size([1, 32, 1])

In [36]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [37]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

# Expand / repeat
#Expand:broadcasting   改变我们对数据的理解，不会主动的复制数据，只会在有需要的时候复制数据，执行速度快，节约内存
#Repeat: memory copied  直接复制数据

In [38]:
a = torch.rand(4,32,14,14)

In [39]:
b.shape

torch.Size([1, 32, 1, 1])

In [40]:
b.expand(4,32,14,14).shape # 只有原来维度为1的地方才可以expand

torch.Size([4, 32, 14, 14])

In [41]:
b.expand(-1,32,-1,-1).shape # -1 表示该位置的维度保持不变，或者自适应的计算所需要的维度

torch.Size([1, 32, 1, 1])

In [43]:
b.expand(-1,32,-1,-4).shape  # bug 可以给负数，但是这个bug已经被facebook修复

torch.Size([1, 32, 1, -4])

In [44]:
b.shape

torch.Size([1, 32, 1, 1])

In [47]:
b.repeat(4,32,1,1).shape  # repeat 接受的参数是每个维度需要拷贝的次数

torch.Size([4, 1024, 1, 1])

In [48]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [49]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

# .t() 转置操作

In [50]:
b.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [53]:
a = torch.randn(3,4) # 只能适用2D的矩阵

In [52]:
a.t()

tensor([[-1.3313, -0.5369, -0.1813],
        [ 1.1260, -0.5531, -1.0167],
        [ 0.5257, -0.5484, -1.3607],
        [-0.9335, -0.7634, -1.6073]])

# Transpose 
交换维度

In [55]:
a = torch.randn(4,3,32,32)

In [56]:
a.shape

torch.Size([4, 3, 32, 32])

In [57]:
a1 = a.transpose(1,3).view(4,3,32,32)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [58]:
a1 = a.transpose(1,3)

In [59]:
a1.shape

torch.Size([4, 32, 32, 3])

In [60]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)

In [61]:
a1.shape

torch.Size([4, 3, 32, 32])

In [62]:
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)

In [63]:
a2.shape

torch.Size([4, 3, 32, 32])

In [64]:
torch.all(torch.eq(a,a1))

tensor(False)

In [65]:
torch.all(torch.eq(a,a2))

tensor(True)

In [66]:
torch.eq(a,a1)

tensor([[[[ True, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False,

# permute

In [67]:
a = torch.rand(4,3,28,28)

In [68]:
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [72]:
b = torch.rand(4,3,28,32)

In [73]:
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [74]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [76]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])