In [1]:
import torch
import numpy as np

In [2]:
a = torch.rand(3,4)

In [3]:
b = torch.rand(4)

In [4]:
a+b

tensor([[0.6588, 0.2173, 0.9272, 1.2026],
        [0.9871, 0.4936, 0.3524, 1.6543],
        [0.9241, 0.9077, 1.1586, 1.5109]])

In [5]:
torch.add(a,b)

tensor([[0.6588, 0.2173, 0.9272, 1.2026],
        [0.9871, 0.4936, 0.3524, 1.6543],
        [0.9241, 0.9077, 1.1586, 1.5109]])

In [6]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

In [7]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [8]:
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(True)

In [9]:
a = torch.ones(2,2)*3

In [10]:
a

tensor([[3., 3.],
        [3., 3.]])

In [11]:
b = torch.ones(2,2)

In [12]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [13]:
torch.matmul(a,b) # 不管是几维的矩阵相乘，都推荐用matmul

tensor([[6., 6.],
        [6., 6.]])

In [14]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [15]:
# an example

In [17]:
a = torch.rand(4,784)

In [19]:
x = torch.rand(4,784)

In [20]:
w = torch.rand(512,784)

In [21]:
(x@w.t()).shape

torch.Size([4, 512])

In [22]:
# 2d以上的矩阵相乘

In [23]:
a = torch.rand(4,3,28,64)

In [24]:
b = torch.rand(4,3,64,32)

In [27]:
torch.mm(a,b).shape

RuntimeError: matrices expected, got 4D, 4D tensors at /tmp/pip-req-build-4baxydiv/aten/src/TH/generic/THTensorMath.cpp:192

In [28]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [29]:
b = torch.rand(4,1,64,32) #第2个维度是1,

In [30]:
torch.matmul(a,b).shape # 会自动进行维度扩展

torch.Size([4, 3, 28, 32])

In [31]:
b = torch.rand(4,64,32)

In [32]:
torch.matmul(a,b).shape

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

In [33]:
a = torch.full([2,2],3)

In [34]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [35]:
a**2

tensor([[9., 9.],
        [9., 9.]])

In [36]:
aa = a**2

In [37]:
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [38]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

In [39]:
# exp log

In [40]:
a = torch.exp(torch.ones(2,2))

In [41]:
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [42]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

In [43]:
# approximation
#   .floor()
#   .ceil()
#   .round()
#   .trunc()
#   .frac()
#

In [44]:
a = torch.tensor(3.14)

In [46]:
a.floor(),a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [47]:
a = torch.tensor(3.499)

In [48]:
a.round()

tensor(3.)

In [49]:
a = torch.tensor(3.5)

In [50]:
a.round()

tensor(4.)

In [51]:
# clamp 
# gradient clipping
# (min)
# (min,max)

In [52]:
grad = torch.rand(2,3)*15

In [53]:
grad.max()

tensor(14.7607)

In [54]:
grad.clamp(10)

tensor([[14.5238, 10.0000, 14.7607],
        [10.8746, 10.0000, 10.0000]])

In [55]:
grad

tensor([[14.5238,  7.7298, 14.7607],
        [10.8746,  1.4192,  1.7286]])

In [56]:
grad.clamp(0,10)

tensor([[10.0000,  7.7298, 10.0000],
        [10.0000,  1.4192,  1.7286]])