In [1]:
import torch
import numpy as np

In [3]:
#  norm
#  mean sum
#  prod
#  max,min,argmin,argmax
#  kthvalue,topk

In [4]:
# 1.noram  范数
#  v.s. normalize,e.g. batch_norm
#  matrix norm v.s. vector norm

In [5]:
a = torch.full([8],1)

In [6]:
b = a.view(2,4)

In [7]:
c = a.view(2,2,2)

In [8]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [10]:
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [11]:
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [12]:
b.norm(1,dim=1)

tensor([4., 4.])

In [13]:
b.norm(2,dim=1)

tensor([2., 2.])

In [14]:
c.norm(1,dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [15]:
c.norm(2,dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [16]:
#统计属性
#  mean
#  sum
#  min
#  max
#  prod 累乘

In [17]:
a = torch.arange(8).view(2,4).float()

In [19]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [20]:
a.min(),a.max(),a.mean(),a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [21]:
a.sum()

tensor(28.)

In [22]:
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [23]:
# argmax,argmin 不给维度时将会把整个tensor的维度打平，然后再取

In [24]:
a = a.view(1,2,4)

In [25]:
a

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [26]:
a.argmax()

tensor(7)

In [27]:
a.argmin()

tensor(0)

In [28]:
a = torch.rand(2,3,4)

In [29]:
a

tensor([[[0.4690, 0.4649, 0.8158, 0.4432],
         [0.6028, 0.4608, 0.5560, 0.0129],
         [0.6990, 0.4098, 0.1728, 0.5053]],

        [[0.1662, 0.3246, 0.3442, 0.2960],
         [0.2317, 0.5242, 0.8331, 0.9192],
         [0.2229, 0.5736, 0.3281, 0.3309]]])

In [30]:
a.argmax()

tensor(19)

In [31]:
a = torch.randn(4,10)

In [32]:
a[0]

tensor([-0.8725, -1.2683, -0.1118,  0.0423,  1.3470,  1.3620,  1.0612,  0.4965,
         0.5426, -1.2933])

In [33]:
a.argmax()

tensor(5)

In [34]:
a.argmax(dim=0)

tensor([1, 3, 1, 0, 0, 0, 0, 2, 1, 3])

In [35]:
a.argmax(dim=1)

tensor([5, 0, 7, 0])

In [36]:
# dim keepdim

In [37]:
a

tensor([[-0.8725, -1.2683, -0.1118,  0.0423,  1.3470,  1.3620,  1.0612,  0.4965,
          0.5426, -1.2933],
        [ 1.1230,  0.8016,  0.3960, -0.3331,  0.7111, -0.2265, -1.1618,  0.0358,
          0.7945, -1.1542],
        [-0.5670, -1.9314, -1.9652, -0.0687, -0.2390,  0.1381,  0.7997,  0.8175,
         -0.4924, -0.5371],
        [ 1.0622,  0.8180,  0.1699, -1.5512,  0.0938,  0.0730, -0.0830, -0.4834,
          0.2805, -0.1597]])

In [39]:
a.max(dim=1)

torch.return_types.max(
values=tensor([1.3620, 1.1230, 0.8175, 1.0622]),
indices=tensor([5, 0, 7, 0]))

In [40]:
a.argmax(dim=1)

tensor([5, 0, 7, 0])

In [41]:
a.max(dim=1,keepdim=True)

torch.return_types.max(
values=tensor([[1.3620],
        [1.1230],
        [0.8175],
        [1.0622]]),
indices=tensor([[5],
        [0],
        [7],
        [0]]))

In [42]:
a.argmax(dim=1,keepdim=True)

tensor([[5],
        [0],
        [7],
        [0]])

In [43]:
#  top-k or k-th

In [44]:
a.topk(3,dim=1)

torch.return_types.topk(
values=tensor([[1.3620, 1.3470, 1.0612],
        [1.1230, 0.8016, 0.7945],
        [0.8175, 0.7997, 0.1381],
        [1.0622, 0.8180, 0.2805]]),
indices=tensor([[5, 4, 6],
        [0, 1, 8],
        [7, 6, 5],
        [0, 1, 8]]))

In [45]:
a.topk(3,dim=1,largest=False)

torch.return_types.topk(
values=tensor([[-1.2933, -1.2683, -0.8725],
        [-1.1618, -1.1542, -0.3331],
        [-1.9652, -1.9314, -0.5670],
        [-1.5512, -0.4834, -0.1597]]),
indices=tensor([[9, 1, 0],
        [6, 9, 3],
        [2, 1, 0],
        [3, 7, 9]]))

In [46]:
a.kthvalue(8,dim=1)# 第8小

torch.return_types.kthvalue(
values=tensor([1.0612, 0.7945, 0.1381, 0.2805]),
indices=tensor([6, 8, 5, 8]))

In [47]:
a.kthvalue(3,dim=1) # 

torch.return_types.kthvalue(
values=tensor([-0.8725, -0.3331, -0.5670, -0.1597]),
indices=tensor([0, 3, 0, 9]))